#!/bin/bash

# Export environment variables
export AT_SECRET=${AT_SECRET}
export AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
export AWS_REGION=${AWS_REGION}
export AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
export DATABASE_URL=${DATABASE_URL}
export ECR_REPOSITORY=${ECR_REPOSITORY}
export EMAIL_OPTIONS_FROM=${EMAIL_OPTIONS_FROM}
export LIGHTSAIL_SERVICE_NAME=${LIGHTSAIL_SERVICE_NAME}
export RT_SECRET=${RT_SECRET}
export SENDGRID_API_KEY=${SENDGRID_API_KEY}
export TK_EMAIL_SECRET=${TK_EMAIL_SECRET}

export API_CORREIOS_URL=${API_CORREIOS_URL}
export APP_PORT=${APP_PORT}
export ENV=${ENV}
export FRONTEND_RECOVER_PASSWORD_URL=${FRONTEND_RECOVER_PASSWORD_URL}
export FRONT_END_URL=${FRONT_END_URL}
export IMAGE_TAG=${IMAGE_TAG}
export JWT_ACCESS_LIFETIME=${JWT_ACCESS_LIFETIME}
export JWT_REFRESH_LIFETIME=${JWT_REFRESH_LIFETIME}
export TK_EMAIL_LIFETIME=${TK_EMAIL_LIFETIME}

export IMAGEM_DO_CONTAINER=$FULL_IMAGE_NAME

escape_sed() {
    echo "$1" | sed -e 's/[\/&]/\\&/g'
}

KEYS=(
    "AT_SECRET"
    "AWS_ACCESS_KEY_ID"
    "AWS_REGION"
    "AWS_SECRET_ACCESS_KEY"
    "DATABASE_URL"
    "ECR_REPOSITORY"
    "EMAIL_OPTIONS_FROM"
    "LIGHTSAIL_SERVICE_NAME"
    "RT_SECRET"
    "SENDGRID_API_KEY"
    "TK_EMAIL_SECRET"
    "API_CORREIOS_URL"
    "APP_PORT"
    "ENV"
    "FRONTEND_RECOVER_PASSWORD_URL"
    "FRONT_END_URL"
    "IMAGE_TAG"
    "JWT_ACCESS_LIFETIME"
    "JWT_REFRESH_LIFETIME"
    "TK_EMAIL_LIFETIME"
    "IMAGEM_DO_CONTAINER"
)

for KEY in "${KEYS[@]}"; do
    VALUE=$(escape_sed "${!KEY}")
    awk -v key="$KEY" -v value="$VALUE" '{ gsub(key, value); print }' $CONFIG_FILE > temp.json && mv temp.json $CONFIG_FILE
done
