-- CreateEnum
CREATE TYPE "RoleEnum" AS ENUM ('CUSTOMER', 'ADMIN');

-- CreateEnum
CREATE TYPE "StatusEnum" AS ENUM ('ACTIVE', 'INACTIVE');

-- CreateEnum
CREATE TYPE "OrderStatus" AS ENUM ('PROCESSING', 'CONCLUDED', 'CANCELED');

-- CreateTable
CREATE TABLE "TB_USER" (
    "id" SERIAL NOT NULL,
    "name" VARCHAR(255) NOT NULL,
    "email" TEXT NOT NULL,
    "password" VARCHAR(255) NOT NULL,
    "refreshToken" VARCHAR(255),
    "recoveryPasswordToken" VARCHAR(255),
    "deletedAt" TIMESTAMPTZ(3),
    "createdAt" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMPTZ(3) NOT NULL,
    "status" "StatusEnum" NOT NULL DEFAULT 'ACTIVE',
    "roleId" INTEGER NOT NULL,
    "mediaId" INTEGER,

    CONSTRAINT "TB_USER_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "TB_ADDRESS" (
    "id" SERIAL NOT NULL,
    "uf" VARCHAR(255) NOT NULL,
    "neighborhood" VARCHAR(255) NOT NULL,
    "city" VARCHAR(255) NOT NULL,
    "street" VARCHAR(255) NOT NULL,
    "cep" VARCHAR(255) NOT NULL,
    "number" VARCHAR(255) NOT NULL,
    "complement" VARCHAR(255),

    CONSTRAINT "TB_ADDRESS_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "TB_ORDER" (
    "id" SERIAL NOT NULL,
    "code" VARCHAR(50) NOT NULL,
    "price" DOUBLE PRECISION NOT NULL,
    "userId" INTEGER NOT NULL,
    "estimatedDelivery" TIMESTAMPTZ(3) NOT NULL,
    "status" "OrderStatus" NOT NULL DEFAULT 'PROCESSING',
    "develiryAddressId" INTEGER,
    "createdAt" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMPTZ(3) NOT NULL,

    CONSTRAINT "TB_ORDER_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "TB_ORDER_PRODUCT" (
    "id" SERIAL NOT NULL,
    "orderId" INTEGER NOT NULL,
    "productId" INTEGER NOT NULL,

    CONSTRAINT "TB_ORDER_PRODUCT_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "TB_PRODUCT" (
    "id" SERIAL NOT NULL,
    "name" VARCHAR(255) NOT NULL,
    "price" DOUBLE PRECISION NOT NULL,
    "stock" INTEGER NOT NULL DEFAULT 0,
    "createdAt" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMPTZ(3) NOT NULL,
    "deletedAt" TIMESTAMPTZ(3),
    "categoryId" INTEGER NOT NULL,

    CONSTRAINT "TB_PRODUCT_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "TB_CATEGORY" (
    "id" SERIAL NOT NULL,
    "name" TEXT NOT NULL,
    "mediaId" INTEGER,
    "createdAt" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deletedAt" TIMESTAMPTZ(3),
    "updatedAt" TIMESTAMPTZ(3) NOT NULL,

    CONSTRAINT "TB_CATEGORY_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "TB_PRODUCT_MEDIA" (
    "id" SERIAL NOT NULL,
    "productId" INTEGER NOT NULL,
    "mediaId" INTEGER NOT NULL,

    CONSTRAINT "TB_PRODUCT_MEDIA_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "TB_MEDIA" (
    "id" SERIAL NOT NULL,
    "url" VARCHAR(255) NOT NULL,

    CONSTRAINT "TB_MEDIA_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "TB_ROLE" (
    "id" SERIAL NOT NULL,
    "createdAt" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deletedAt" TIMESTAMPTZ(3),
    "name" "RoleEnum" NOT NULL,
    "status" "StatusEnum" NOT NULL DEFAULT 'ACTIVE',

    CONSTRAINT "TB_ROLE_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "TB_USER_email_key" ON "TB_USER"("email");

-- CreateIndex
CREATE UNIQUE INDEX "TB_ORDER_code_key" ON "TB_ORDER"("code");

-- CreateIndex
CREATE UNIQUE INDEX "TB_CATEGORY_name_key" ON "TB_CATEGORY"("name");

-- CreateIndex
CREATE UNIQUE INDEX "TB_ROLE_name_key" ON "TB_ROLE"("name");

-- AddForeignKey
ALTER TABLE "TB_USER" ADD CONSTRAINT "TB_USER_roleId_fkey" FOREIGN KEY ("roleId") REFERENCES "TB_ROLE"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TB_USER" ADD CONSTRAINT "TB_USER_mediaId_fkey" FOREIGN KEY ("mediaId") REFERENCES "TB_MEDIA"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TB_ORDER" ADD CONSTRAINT "TB_ORDER_develiryAddressId_fkey" FOREIGN KEY ("develiryAddressId") REFERENCES "TB_ADDRESS"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TB_ORDER" ADD CONSTRAINT "TB_ORDER_userId_fkey" FOREIGN KEY ("userId") REFERENCES "TB_USER"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TB_ORDER_PRODUCT" ADD CONSTRAINT "TB_ORDER_PRODUCT_orderId_fkey" FOREIGN KEY ("orderId") REFERENCES "TB_ORDER"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TB_ORDER_PRODUCT" ADD CONSTRAINT "TB_ORDER_PRODUCT_productId_fkey" FOREIGN KEY ("productId") REFERENCES "TB_PRODUCT"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TB_PRODUCT" ADD CONSTRAINT "TB_PRODUCT_categoryId_fkey" FOREIGN KEY ("categoryId") REFERENCES "TB_CATEGORY"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TB_CATEGORY" ADD CONSTRAINT "TB_CATEGORY_mediaId_fkey" FOREIGN KEY ("mediaId") REFERENCES "TB_MEDIA"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TB_PRODUCT_MEDIA" ADD CONSTRAINT "TB_PRODUCT_MEDIA_productId_fkey" FOREIGN KEY ("productId") REFERENCES "TB_PRODUCT"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TB_PRODUCT_MEDIA" ADD CONSTRAINT "TB_PRODUCT_MEDIA_mediaId_fkey" FOREIGN KEY ("mediaId") REFERENCES "TB_MEDIA"("id") ON DELETE CASCADE ON UPDATE CASCADE;
